# Generated by Django 3.2.1 on 2023-09-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libraryDB',
            fields=[
                ('Book_id', models.AutoField(primary_key=True, serialize=False)),
                ('Book_Name', models.CharField(max_length=50)),
                ('Book_author', models.CharField(max_length=50)),
                ('Book_price', models.IntegerField()),
            ],
        ),
    ]
